### ISSUE TITLE
'Reporting a problem' page doesn't tell the user how to report a problem

### ISSUE THREAD

**Issue by jmcvea** [IBM-Bluemix-Docs/MessageHub#1]
The page at https://console.bluemix.net/docs/services/MessageHub/messagehub109.html#report_problem provides a list of information to gather, but doesn't tell the user how to submit an actual problem report.

The page should include references for the user on where/how to submit a problem report with the gathered information.

**Comment by karen-rodgers** [comment]
Hi @jmcvea 
Thanks a lot for your update. I've incorporated it on production here: https://console.bluemix.net/docs/services/MessageHub/messagehub109.html#report_problem

In your pull request, the 2nd link at the very end goes back to the same Message Hub page (https://console.bluemix.net/docs/services/MessageHub/messagehub109.html#report_problem). Instead I've added a link to https://console.bluemix.net/docs/support/index.html#open-ticket.
Please let me know if you'd like this link changed to something else.

**Comment by jmcvea** [comment]
Thanks @karen-rodgers. The second link was a copy/paste error. Thanks for correcting it!
